apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-app-depoyment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fast-app
  template:
    metadata:
      labels:
        app: fast-app
    spec:
      containers:
        - name: trabalho-final
          image: brenor2d2/trabalho-final
          ports:
            - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: fast-service
spec:
  selector:
    app: fast-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer